import 'bootstrap/dist/css/bootstrap.css';
import { Montserrat } from "next/font/google";
import "./globals.css";
import BootstrapClient from '@/components/BootstrapClient';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <BootstrapClient />
        <Footer />
    </body>
    </html>
  );
}
